namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassContainer
{
    ITEM_SUBCLASS_CONTAINER = 0,
    ITEM_SUBCLASS_SOUL_CONTAINER = 1,
    ITEM_SUBCLASS_HERB_CONTAINER = 2,
    ITEM_SUBCLASS_ENCHANTING_CONTAINER = 3,
    ITEM_SUBCLASS_ENGINEERING_CONTAINER = 4,
    ITEM_SUBCLASS_GEM_CONTAINER = 5,
    ITEM_SUBCLASS_MINING_CONTAINER = 6,
    ITEM_SUBCLASS_LEATHERWORKING_CONTAINER = 7,
    ITEM_SUBCLASS_INSCRIPTION_CONTAINER = 8
}