namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassArmor
{
    ITEM_SUBCLASS_ARMOR_MISCELLANEOUS = 0,
    ITEM_SUBCLASS_ARMOR_CLOTH = 1,
    ITEM_SUBCLASS_ARMOR_LEATHER = 2,
    ITEM_SUBCLASS_ARMOR_MAIL = 3,
    ITEM_SUBCLASS_ARMOR_PLATE = 4,
    ITEM_SUBCLASS_ARMOR_BUCKLER = 5,
    ITEM_SUBCLASS_ARMOR_SHIELD = 6,
    ITEM_SUBCLASS_ARMOR_LIBRAM = 7,
    ITEM_SUBCLASS_ARMOR_IDOL = 8,
    ITEM_SUBCLASS_ARMOR_TOTEM = 9,
    ITEM_SUBCLASS_ARMOR_SIGIL = 10
}