namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassGlyph
{
    ITEM_SUBCLASS_GLYPH_WARRIOR = 1,
    ITEM_SUBCLASS_GLYPH_PALADIN = 2,
    ITEM_SUBCLASS_GLYPH_HUNTER = 3,
    ITEM_SUBCLASS_GLYPH_ROGUE = 4,
    ITEM_SUBCLASS_GLYPH_PRIEST = 5,
    ITEM_SUBCLASS_GLYPH_DEATH_KNIGHT = 6,
    ITEM_SUBCLASS_GLYPH_SHAMAN = 7,
    ITEM_SUBCLASS_GLYPH_MAGE = 8,
    ITEM_SUBCLASS_GLYPH_WARLOCK = 9,
    ITEM_SUBCLASS_GLYPH_DRUID = 11
}