namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassTradeGoods
{
    ITEM_SUBCLASS_TRADE_GOODS = 0,
    ITEM_SUBCLASS_PARTS = 1,
    ITEM_SUBCLASS_EXPLOSIVES = 2,
    ITEM_SUBCLASS_DEVICES = 3,
    ITEM_SUBCLASS_JEWELCRAFTING = 4,
    ITEM_SUBCLASS_CLOTH = 5,
    ITEM_SUBCLASS_LEATHER = 6,
    ITEM_SUBCLASS_METAL_STONE = 7,
    ITEM_SUBCLASS_MEAT = 8,
    ITEM_SUBCLASS_HERB = 9,
    ITEM_SUBCLASS_ELEMENTAL = 10,
    ITEM_SUBCLASS_TRADE_GOODS_OTHER = 11,
    ITEM_SUBCLASS_ENCHANTING = 12,
    ITEM_SUBCLASS_MATERIAL = 13,
    ITEM_SUBCLASS_ARMOR_ENCHANTMENT = 14,
    ITEM_SUBCLASS_WEAPON_ENCHANTMENT = 15
}