namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassRecipe
{
    ITEM_SUBCLASS_BOOK = 0,
    ITEM_SUBCLASS_LEATHERWORKING_PATTERN = 1,
    ITEM_SUBCLASS_TAILORING_PATTERN = 2,
    ITEM_SUBCLASS_ENGINEERING_SCHEMATIC = 3,
    ITEM_SUBCLASS_BLACKSMITHING = 4,
    ITEM_SUBCLASS_COOKING_RECIPE = 5,
    ITEM_SUBCLASS_ALCHEMY_RECIPE = 6,
    ITEM_SUBCLASS_FIRST_AID_MANUAL = 7,
    ITEM_SUBCLASS_ENCHANTING_FORMULA = 8,
    ITEM_SUBCLASS_FISHING_MANUAL = 9,
    ITEM_SUBCLASS_JEWELCRAFTING_RECIPE = 10,
    ITEM_SUBCLASS_INSCRIPTION_TECHNIQUE = 11
}