namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassConsumable
{
    ITEM_SUBCLASS_CONSUMABLE = 0,
    ITEM_SUBCLASS_POTION = 1,
    ITEM_SUBCLASS_ELIXIR = 2,
    ITEM_SUBCLASS_FLASK = 3,
    ITEM_SUBCLASS_SCROLL = 4,
    ITEM_SUBCLASS_FOOD_DRINK = 5,
    ITEM_SUBCLASS_ITEM_ENHANCEMENT = 6,
    ITEM_SUBCLASS_BANDAGE = 7,
    ITEM_SUBCLASS_CONSUMABLE_OTHER = 8
}