namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassGem
{
    ITEM_SUBCLASS_GEM_RED = 0,
    ITEM_SUBCLASS_GEM_BLUE = 1,
    ITEM_SUBCLASS_GEM_YELLOW = 2,
    ITEM_SUBCLASS_GEM_PURPLE = 3,
    ITEM_SUBCLASS_GEM_GREEN = 4,
    ITEM_SUBCLASS_GEM_ORANGE = 5,
    ITEM_SUBCLASS_GEM_META = 6,
    ITEM_SUBCLASS_GEM_SIMPLE = 7,
    ITEM_SUBCLASS_GEM_PRISMATIC = 8
}