namespace TrinityCore._3._3._5.ClientLibrary.WorldState.Enums;

[Flags]
public enum ItemSubclassWeapon
{
    ITEM_SUBCLASS_WEAPON_AXE = 0,
    ITEM_SUBCLASS_WEAPON_AXE2 = 1,
    ITEM_SUBCLASS_WEAPON_BOW = 2,
    ITEM_SUBCLASS_WEAPON_GUN = 3,
    ITEM_SUBCLASS_WEAPON_MACE = 4,
    ITEM_SUBCLASS_WEAPON_MACE2 = 5,
    ITEM_SUBCLASS_WEAPON_POLEARM = 6,
    ITEM_SUBCLASS_WEAPON_SWORD = 7,
    ITEM_SUBCLASS_WEAPON_SWORD2 = 8,
    ITEM_SUBCLASS_WEAPON_OBSOLETE = 9,
    ITEM_SUBCLASS_WEAPON_STAFF = 10,
    ITEM_SUBCLASS_WEAPON_EXOTIC = 11,
    ITEM_SUBCLASS_WEAPON_EXOTIC2 = 12,
    ITEM_SUBCLASS_WEAPON_FIST_WEAPON = 13,
    ITEM_SUBCLASS_WEAPON_MISCELLANEOUS = 14,
    ITEM_SUBCLASS_WEAPON_DAGGER = 15,
    ITEM_SUBCLASS_WEAPON_THROWN = 16,
    ITEM_SUBCLASS_WEAPON_SPEAR = 17,
    ITEM_SUBCLASS_WEAPON_CROSSBOW = 18,
    ITEM_SUBCLASS_WEAPON_WAND = 19,
    ITEM_SUBCLASS_WEAPON_FISHING_POLE = 20
}